export const skills = [
  "ASP.NET Core",
  "ASP.NET MVC",
  "SQL",
  "C",
  "Javascript",
  "ReactJS",
  "React Native",
  "Kubernetes",
  "Infrastructure",
  "Terraform",
  "Go",
  "Devops",
  "Sysadmin",
  "Azure",
  "HTML",
  "Amazon Web Services",
  "Python",
  "Ruby On Rails",
  "Node JS",
  "Java",
  "NoSQL",
  "Concurrency",
  "Distributed Computing",
  "Database Design",
  "React",
  "Heroku",
  "PostgreSQL",
  "JQuery",
  "Ruby On Rails 3",
  "PHP",
  "Angular",
  "Github",
  "Rest",
  "Typescript",
  "CSS",
  "Ruby",
  "Ansible",
  "Docker",
  "User Interface",
  "User Experience",
  "Adobe",
  "SQL Server",
  "Agile",
  "Angularjs",
  "Ecmascript 6",
  "Abap",
  "Sapui 5",
  "HTML 5",
  "Odata",
  "IOS",
  "Objective C",
  "Swift",
  "Watch OS",
  "IPhone",
  "Sass",
  "Responsive Design",
  "Android",
  "Mobile",
  "Kotlin",
  "RabbitMQ",
  "Gin Gonic",
  "Ember JS",
  "Microservices",
  "Automation",
  "TDD",
  "ASP.NET",
  "Vue JS",
  "Apache",
  "Coldfusion",
  "CFC",
  "SAAS",
  "React JS",
  "Django",
  "Google App Engine",
  "D3 JS",
  "Frameworks",
  "Pixi JS",
  "Hadoop",
  "Apache Spark",
  "Cloud",
  "Testing",
  "QA",
  "Apache Flink",
  "Apache Kafka",
  "Ionic Framework",
  "Chromium",
  "Googletest",
  "Cryptocurrency",
  "Design",
  "Docker Compose",
  "Rancher",
  "GitLab CI",
  "Linux",
  "AWS Lambda",
  "Drupal",
  "Drupal 8",
  "Symfony",
  "MySQL",
  "Drupal 7",
  "MongoDB",
  "Project Management",
  "Wordpress",
  "Security",
  "Networking",
  "A/B Testing",
  "Product Management",
  "JBoss",
  "Financial",
  "Scientist",
  "Elasticsearch",
  "Flask",
  "API",
  "Flask Restful",
  "Redis",
  "Containers",
  "Camera",
  "Java Bytecode ASM",
  "Trust Zone",
  "Elixir",
  "Rubyonrails",
  "Git",
  "Static Analysis",
  "MSVC",
  "MSYS2",
  "Perl",
  "Elm",
  "Golang",
  "Autotools",
  "Python 2",
  "Make",
  "Build",
  "OpenJDK",
  "Pandas",
  "scikit-learn",
  "Numpy",
  "MS Access",
  "Reporting Services",
  "Magento",
  "Ecommerce",
  "Web Services",
  "GCP",
  "Kafka",
  "Jira",
  "Selenium",
  "Automated Tests",
  "Load Testing",
  "Stress Testing",
  "E2E Testing",
  "AI",
  "Puppet",
  "Bigdata",
  "Cassandra",
  "P2P",
  ".NET Core",
  "Scala",
  "Puppeteer",
  "Test Driven Development",
  "Ruby On Rails 4",
  "Datadog",
  "Amazon Cloudformation",
  "NLP",
  "Google Cloud Platform",
  "IOS Autolayout",
  "Profiling",
  "View Debugging",
  "Knockout JS",
  "Leaflet",
  "Google Maps",
  "Geolocation",
  "ETL",
  "Pytorch",
  "Functional Programming",
  "Scala Cats",
  "FS 2",
  "http4s",
  "Visual Studio 2013",
  "SQL Server 2012",
  "MobX",
  ".NET",
  "Peoplecode",
  "AWS",
  "Graphql",
  "Unit Testing",
  "MVC",
  "CMake",
  "ZeroMQ",
  "Hanami",
  "Xamarin",
  "Chef",
  "Bash",
  "Multithreading",
  "Java EE",
  "Database",
  "MEAN",
  "MERN",
  "Knative",
  "Serverless",
  "GKE",
  "Continuous Integration",
  "Continuous Delivery",
  "CI/CD",
  "Solidus",
  "Spree",
  "Azure DevOps",
  "OpenAPI",
  "Jupyter Lab",
  "Migration",
  "Flutter",
  "WebRTC",
  "Serverless Framework",
  "Firebase",
  "Burp",
  "IOT",
  "Single Page Application",
  "SPA",
  "Algorithm",
  "Machine Learning",
  "Optimization",
  "CSS 3",
  "Less",
  "Socket IO",
  "XML",
  "Amazon DynamoDB",
  "Coffeescript",
  "Redux",
  "Spring",
  "R",
  "Shopify",
  "Mongoid",
  "Neo4j",
  "Powershell",
  "Amazon EC2",
  "Maven",
  "Jenkins",
  "Scrum",
  "Laravel",
  "RSpec",
  "Asterisk",
  "VoIP",
  "VMware",
  "Spring Data JPA",
  "Spring Boot",
  "Haskell",
  "Websphere",
  "2D",
  "3D",
  "Game Development",
  "RocksDB",
  "Graph Databases",
  "System",
  "Linux Kernel",
  "Hibernate",
  "Network Programming",
  "Distributed System",
  "Activiti",
  "Progressive Web Apps",
  "Visual Studio",
  "FFmpeg",
  "Salt Stack",
  "ExtJS",
  "SciPy",
  "API Design",
  "Camunda",
  "Billing",
  "Python 3",
  "ASP.NET Web API",
  "Spark",
  "Amazon Kinesis",
  "Clojure",
  "Frontend",
  "Groovy",
  "Forgerock",
  "UI Testing",
  "Lead",
  "Lead Generation",
  "Architecture",
  "Oracle",
  "React Redux",
  "Windows",
  "GRPC",
  "SRE",
  "Database Administration",
  "Kentico",
  "Postman",
  "Appium",
  "Integration Testing",
  "Spring MVC",
  "JSON",
  "Data Structures",
  "Encryption",
  "Bitbucket",
  "Ecmascript 7",
  "Sales",
  "Relational Database",
  "OOP",
  "Data Visualization",
  "Web Applications",
  "Embedded",
  "Webpack",
  "Erlang",
  "PHP 7",
  "Magento 2",
  "Symfony 2",
  "NGINX",
  "WP CLI",
  "Tableau",
  "Backend",
  "SEO",
  "SEM",
  "Scripting",
  "Varnish",
  "MacOS",
  "GUI",
  "T-SQL",
  "OSX",
  "JVM",
  "Java 8",
  "IIS",
  "Windows Server",
  "Django Rest Framework",
  "Technical Interviewing",
  "Yocto",
  "Cucumber",
  "Typo 3",
  "Typoscript",
  "Fluid",
  "Tomcat",
  "Middleware",
  "Shiny",
  "Ossec",
  "Woocommerce",
  "Styled Components",
  "Jest",
  "Apollo",
  "Mongo",
  "Gatsby",
  "API Gateway",
  "Amazon Cognito",
  "AWS Sam CLI",
  "Extbase",
  "Okta",
  "SOC",
  "MDM",
  "Data Warehouse",
  "JSP",
  "Business Intelligence",
  "JavaFX",
  "Swing",
  "SwingX",
  "CherryPy",
  "Model View Controller",
  "Guidewire",
  "Sitecore",
  "Manual Testing",
  "Rust",
  "Babel",
  "Unix",
  "Data Extraction",
  "Reverse Engineering",
  "Express",
  "Xcode",
  "HTTP",
  "SSL",
  "LDAP",
  "SSH",
  "BabelJS",
  "Sequel",
  "Cuba",
  "Sinatra",
  "Agile Project Management",
  "Material Ui",
  "2D Games",
  "HTML5 Canvas",
  "React Native Android",
  "React Native Ios",
  "Visual Studio App Center",
  "Embedded Linux",
  "Raspberry Pi",
  "Phaser Framework",
  "Reactive Programming",
  "Autolayout",
  "Deployment",
  "Phoenix Framework",
  "ROS",
  "Robotics",
  "Web Crawler",
  "Web Scraping",
  "Mybatis",
  "CQRS",
  "Domain Driven Design",
  "Computational Finance",
  "WPF",
  "Unity",
  "VPN",
  "Configuration Management",
  "Salesforce",
  "Apex",
  "Alfresco",
  "Data Science",
  "Data Analysis",
  "Aurelia",
  "Material Design",
  "Digital Design",
  "ASP.NET MVC 5",
  "Apt",
  "Tableau Online",
  "Tableau Server",
  "Tableau Public",
  "Angular 6",
  "Angular Reactive Forms",
  "Reactive Forms",
  "RxJS",
  "Open Source",
  "Documentation",
  "Event Sourcing",
  "Continuous Deployment",
  "Delivery Pipeline",
  "Stripe Payments",
  "Payment Gateway",
  "Payment",
  "Event Driven",
  "Entity Framework",
  "Elastic Beats",
  "Data Ingestion",
  "Logging",
  "Metrics",
  "Observable",
  "Debugging",
  "Typography",
  "NodeJS",
  "Splunk",
  "Amazon Redshift",
  "PrestoDB",
  "Airflow",
  "Elasticsearch 5",
  "SFTP",
  "FTP",
  "Rails",
  "Elastic Beanstalk",
  "Game Engine",
  "Marionette",
  "Photoshop",
  "Meter",
  "Data Modeling",
  "Visualforce",
  "Salesforce Lightning",
  "Reactivex",
  "NgRx",
  "Websocket",
  "CakePHP",
  "Geospatial",
  "Math",
  "Storybook",
  "Cypress",
  "Cryptography",
  "Oauth 2.0",
  "SHA",
  "Glassfish",
  "CouchDB",
  "Hybris",
  "Webforms",
  "Linear Algebra",
  "Computational Geometry",
  "Phoenix",
  "Postgis",
  "ASP.NET Web API 2",
  "Acumatica",
  "Enterprise Architect",
  "Truffle",
  "GraalVM",
  "Twitter Bootstrap",
  "ISO 8583",
  "JPOS",
  "Lamp",
  "Akka",
  "Databricks",
  "Visual Studio 2017",
  "Visual Studio 2019",
  "Vagrant",
  "Locust",
  "Xamarin Forms",
  "UX",
  "UI",
  "Designer",
  "Redux Saga",
  "Enzyme",
  "Excel",
  "GIS",
  "Jupyter Notebook",
  "UIkit",
  "SwiftUI",
  "Combine",
  "Unity 3D",
  "Node",
  "Grafana",
  "Snowflake Datawarehouse",
  "Multivariate Testing",
  "Figma API",
  "Rendering",
  "Metal",
  "OpenGL",
  "Virtual Reality",
  "JMeter",
  "P5 JS",
  "Performance",
  "Performance Testing",
  "VB.NET",
  "E Commerce",
  "Artificial Intelligence",
  "Hybrid Mobile App",
  "Ionic",
  "Sidekiq",
  "IntelliJ IDEA",
  "Blockchain",
  "Mesos",
  "CSS In JS",
  "Backup",
  "AEM",
  "SFDC",
  "Enterprise",
  "Application Security",
  "PCI",
  "Penetration Testing",
  "Tax",
  "JEE",
  "Oracle ADF",
  "Salesforce Service Cloud",
  "Salesforce Communities",
  "Google Kubernetes Engine",
  "GCC",
  "Boost Asio",
  "WCF",
  "Product",
  "Search",
  "Solr",
  "Hosting",
  "Chatbot",
  "Dialogflow",
  "Ionic 3",
  "Energy",
  "Modeling",
  "Hangfire",
  "SQL Server 2016",
  "Teamcity",
  "Activerecord",
  "Types",
  "Emscripten",
  "Vulkan",
  "Android Studio",
  "Cluster",
  "TPM",
  "Fault Tolerance",
  "Messaging",
  "Hapi",
  "V8",
  "Monkeypatching",
  "Google Bigquery",
  "Pug",
  "Time Series",
  "Forecasting",
  "JestJS",
  "Qt",
  "Springboot",
  "Scrapy",
  "Algorithms",
  "Heuristics",
  "Mapreduce",
  "Pipeline",
  "Next JS",
  "NPM",
  "C-CDA",
  "HL7 FHIR",
  "ROR",
  "Google Chrome Devtools",
  "Dom Manipulation",
  "PySpark",
  "Websecurity",
  "Network Protocols",
  "Kotlin Android Extensions",
  "EDI",
  "Webassembly",
  "Graphics",
  "WebGL",
  "Cloud Security",
  "Three JS",
  "Redhat",
  "Celery",
  "Raptor",
  "C#",
  "OpenCV",
  "SQLite",
  "Opensource",
  "Data",
  "Revit",
  "Revit API",
  "Autodesk",
  "Autocad",
  "Plugins",
  "Image Processing",
  "Computer Vision",
  "Sketch 3",
  "Writing",
  "Lucene",
  "CUDA",
  "Native",
  "JS",
  "Analytics",
  "Toolchain",
  "GDB",
  "Virtualization",
  "Beta",
  "Spring Cloud",
  "Static",
  "Servicenow",
  "SAML",
  "OpenID Connect",
  "Vue",
  "Ubuntu",
  "LXC",
  "Regression Testing",
  "Testcase",
  "JRuby",
  "cmocka",
  "Pact",
  "GitLab",
  "Travis CI",
  "Roadmap",
  "Apex Code",
  "Soql",
  "Pentaho",
  "Sails JS",
  "Web Frontend",
  "Cisco",
  "Juniper",
  "Markdown",
  "Veeam",
  "Vsto",
  "Ruby On Rails 5",
  "Communication",
  ".NET Core 2",
  "Star Schema",
  "React Hooks",
  "Access Control",
  "Selenium Webdriver",
  "Talend",
  "Power BI",
  "Docker Swarm",
  "Docker EE",
  "BPMN",
  "Authentication",
  "Cordova",
  "System Administration",
  "Espresso",
  "MS Office",
  "Google Apps",
  "Implementation",
  "Content Management System",
  "Confluence",
  "App",
  "TCP",
  "Routing",
  "Grape",
  "Amazon S3",
  "Customer",
  "Rest API",
  "Mapbox GL JS",
  "Privacy",
  "Ember Data",
  "Ember CLI",
  "F",
  "Doobie",
  "ATG",
  "Shopping Cart",
  "DNS",
  "GPO",
  "DHCP",
  "IAAS",
  "Ethereum",
  "k6",
  "Developer Tools",
  "SOA",
  "Kanban",
  "Google Sheets",
  "Amazon Athena",
  "BDD",
  "Circleci",
  "Web Development Server",
  "Instrumentation",
  "Protocol Buffers",
  "TCPdump",
  "SDK",
  "Solidity",
  "Prometheus",
  "ASP Classic",
  "HTTPS",
  "CDN",
  "Proxy",
  "Digital Ocean",
  "Cloud Platform",
  "Playframework 2",
  "B2B",
  "On Prem",
  "Laravel 5",
  "PHP 7",
  "State Management",
  "Jhipster",
  "Openshift",
  "Qunit",
  "STM32",
  "Can Bus",
  "Bootloader",
  "Autoscaling",
  "Snowflake",
  "Pytest",
  "Fabric",
  "Pyomo",
  "CPLEX",
  "SQLalchemy",
  "Sketchapp",
  "Banking",
  "Syslog",
  "Syslog NG",
  "Amazon Cloudwatch",
  "VPC",
  "Protocols",
  "Version Control",
  "Spark Streaming",
  "Olap",
  "Salt",
  "Closure",
  "Ajax",
  "Streaming",
  "Video Streaming",
  "VBA",
  "Sap",
  "Publish Subscribe",
  "Netlify",
  "Amazon Lightsail",
  "Electron",
  "Liquid",
  "Balsamiq",
  "Python 3",
  "Jquery UI",
  "Azure Cloud Services",
  "Azure SQL Database",
  "Scientific Software",
  "Numerical Analysis",
  "MPI",
  "Authorization",
  "Schema",
  "Binary",
  "Fuzzing",
  "RDBMS",
  "Bootstrap 4",
  "DBA",
  "IPv6",
  "Protractor",
  "ActiveMQ",
  "Clojurescript",
  "Reagent",
  "Polymer",
  "Solid",
  "Functional Testing",
  "Black Box Testing",
  "Statistics",
  "HAML",
  "Azure Functions",
  "Hazelcast",
  "Struts",
  "Junit",
  "Quantitative Finance",
  "Back",
  "Integration",
  "DDD",
  "Episerver",
  "Ektron",
  "Umbraco",
  "Video",
  "Visual Web Gui",
  "Gradle",
  "Audio",
  "Speech",
  "Signal Processing",
  "Voice Recognition",
  "RxSwift",
  "GraphQL JS",
  "IETF netconf",
  "Codeception",
  "Browserstack",
  "Webdriver",
  "Restful Architecture",
  "Capybara",
  "Presentation",
  "Ionic 4",
  "Matillion",
  "SQL Data Warehouse",
  "Software Design",
  "Lambda",
  "Ecmascript 2017",
  "Graph",
  "Nodes",
  "Real Time",
  "Matching",
  "TCP IP",
  "Alm",
  "Angular 8",
  "GNU Toolchain",
  "Alteryx",
  "Front End",
  "Packer",
  "Mpls",
  "Angular 7",
  "Mulesoft",
  "ESB",
  "Fast AI",
  "Analysis",
  "MDX",
  "SSAS Tabular",
  "Dax",
  "Servlets",
  "GWT",
  "Blazor",
  "Windows Services",
  "Com",
  "Async Await",
  "Saga",
  "Gwtp",
  "Bixby",
  "Alexa Skill",
  "Voice",
  "Network Security",
  "Health Kit",
  "Turbolinks",
  "Shell",
  "Monitoring",
  "Reliability",
  "CI",
  "CD",
  "Platform",
  "Back End",
  "Web Deployment",
  "Salesforce Commerce Cloud",
  "Demandware",
  "Version",
  "Control",
  "RCPP",
  "Azure Service Fabric",
  "React Fullstack",
  "Postgres",
  "Datastore",
  "Database Performance",
  "Amazon Ecs",
  "React Apollo",
  "Re Engineering",
  "Delphi",
  "Delphi 2007",
  "Delphi 10 3 Rio",
  "SDLC",
  "Elastic Stack",
  "Logstash",
  "GSuite",
  "Sharepoint",
  "WebAPI",
  "SPFX",
  "Unsupervised Learning",
  "Active Directory",
  "Azure Active Directory",
  "Snowflake Data Warehouse",
  "Cross Browser",
  "DynamoDB",
  "PAAS",
  "Clickhouse",
  "Bitcoin",
  "ERC-20",
  "Openstack",
  "Infrastructure As A Code",
  "Core Data",
  "UIStoryboard",
  "Core Graphics",
  "Software",
  "Drivers",
  "Operating System",
  "Octopus Deploy",
  "Jasmine",
  "Azure Resource Manager",
  "Debian",
  "Wordpress Theming",
  "Gherkin",
  "Machine Code",
  "Pulumi",
  "Tensorflow",
  "Web",
  "Secure Coding",
  "Payments",
  "Basecamp",
  "Zendesk",
  "Blazor Server Side",
  "Blazor Client Side",
  "Finance",
  "Digital",
  "Spacy",
  "Regression",
  "Keras",
  "Cluster Analysis",
  "Permanent",
  "Azureservicebus",
  "Azure CosmosDB",
  "Appinsights",
  "OWASP",
  "Spring Security",
  "Computer Science",
  "Time Complexity",
  "Sorting",
  "Maintenance",
  "Ranorex",
  "Google Chrome Extension",
  "Zuora",
  "Sparql",
  "RDF",
  "Anypoint Studio",
  "Kubernetes Helm",
  "Nightwatch JS",
  "Socialengine",
  "Exchange Server",
  "Antivirus",
  "Standards Compliance",
  "AWS API Gateway",
  "Infrastructure As Code",
  "Marketo",
  "Trello",
  "Kibana",
  "Ruby On Rails 6",
  "Eclipse",
  "jBPM",
  "NetSuite",
  "ERP",
  "Spinnaker",
  "Wireframe",
  "Symfony 4",
  "Cluster Computing",
  "Azure Virtual Machine",
  "Lit Element",
  "Web Component",
  "Atlassian Sourcetree",
  "Fisheye",
  "Mobile Application",
  "Build Automation",
  "ZFS",
  "Elk",
  "Dropbox",
  "Tidyverse",
  "Tornado",
  "Config",
  "SAML 2.0",
  "Angular 5",
  "Symfony 3",
  "Leaf",
  "Creative Cloud",
  "Discord",
  "Figma",
  "Sketch",
  "Invision",
  "MVVM",
  "Java Stream",
  "Common Lisp",
  "Scheme",
  "x86",
  "XGBoost",
  "Bayesian",
  "TimescaleDB",
  "RxJava",
  "InfluxDB",
  "Object",
  "IBM Cloud",
  "Alibaba Cloud",
  "Android NDK",
  "ML.NET",
  "ML.NET Model Builder",
  "Shibboleth",
  "Single Sign On",
  "SSO",
  "SSIS 2012",
  "Multi Threaded",
  "Dart",
  "Istio",
  "Cython",
  "Responsive",
  "Linked Data",
  "Webgl 2",
  "PCI DSS",
  "Graphite",
  "Mapbox",
  "Telephony",
  "SIP",
  "Amazon Redshift Spectrum",
  "Object Oriented Analysis",
  "Marketing",
  "Product Marketing",
  "Affiliate Marketing",
  "Go to market",
  "Product launch",
  "Blogs",
  "Caching",
  "Semantic Web",
].sort()
